// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "lcmtypes/bayesian_data_training_pair.h"

static int __bayesian_data_training_pair_hash_computed;
static uint64_t __bayesian_data_training_pair_hash;

uint64_t __bayesian_data_training_pair_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __bayesian_data_training_pair_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = __bayesian_data_training_pair_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x0e86f2ac9014a632LL
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __bayesian_data_training_pair_get_hash(void)
{
    if (!__bayesian_data_training_pair_hash_computed) {
        __bayesian_data_training_pair_hash = (int64_t)__bayesian_data_training_pair_hash_recursive(NULL);
        __bayesian_data_training_pair_hash_computed = 1;
    }

    return __bayesian_data_training_pair_hash;
}

int __bayesian_data_training_pair_encode_array(void *buf, int offset, int maxlen, const bayesian_data_training_pair *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, p[element].training_x_, 5);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].training_y_), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int bayesian_data_training_pair_encode(void *buf, int offset, int maxlen, const bayesian_data_training_pair *p)
{
    int pos = 0, thislen;
    int64_t hash = __bayesian_data_training_pair_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __bayesian_data_training_pair_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __bayesian_data_training_pair_encoded_array_size(const bayesian_data_training_pair *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __double_encoded_array_size(p[element].training_x_, 5);

        size += __double_encoded_array_size(&(p[element].training_y_), 1);

    }
    return size;
}

int bayesian_data_training_pair_encoded_size(const bayesian_data_training_pair *p)
{
    return 8 + __bayesian_data_training_pair_encoded_array_size(p, 1);
}

int __bayesian_data_training_pair_decode_array(const void *buf, int offset, int maxlen, bayesian_data_training_pair *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, p[element].training_x_, 5);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].training_y_), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __bayesian_data_training_pair_decode_array_cleanup(bayesian_data_training_pair *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __double_decode_array_cleanup(p[element].training_x_, 5);

        __double_decode_array_cleanup(&(p[element].training_y_), 1);

    }
    return 0;
}

int bayesian_data_training_pair_decode(const void *buf, int offset, int maxlen, bayesian_data_training_pair *p)
{
    int pos = 0, thislen;
    int64_t hash = __bayesian_data_training_pair_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __bayesian_data_training_pair_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int bayesian_data_training_pair_decode_cleanup(bayesian_data_training_pair *p)
{
    return __bayesian_data_training_pair_decode_array_cleanup(p, 1);
}

int __bayesian_data_training_pair_clone_array(const bayesian_data_training_pair *p, bayesian_data_training_pair *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __double_clone_array(p[element].training_x_, q[element].training_x_, 5);

        __double_clone_array(&(p[element].training_y_), &(q[element].training_y_), 1);

    }
    return 0;
}

bayesian_data_training_pair *bayesian_data_training_pair_copy(const bayesian_data_training_pair *p)
{
    bayesian_data_training_pair *q = (bayesian_data_training_pair*) malloc(sizeof(bayesian_data_training_pair));
    __bayesian_data_training_pair_clone_array(p, q, 1);
    return q;
}

void bayesian_data_training_pair_destroy(bayesian_data_training_pair *p)
{
    __bayesian_data_training_pair_decode_array_cleanup(p, 1);
    free(p);
}

int bayesian_data_training_pair_publish(lcm_t *lc, const char *channel, const bayesian_data_training_pair *p)
{
      int max_data_size = bayesian_data_training_pair_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = bayesian_data_training_pair_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _bayesian_data_training_pair_subscription_t {
    bayesian_data_training_pair_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void bayesian_data_training_pair_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    bayesian_data_training_pair p;
    memset(&p, 0, sizeof(bayesian_data_training_pair));
    status = bayesian_data_training_pair_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding bayesian_data_training_pair!!!\n", status);
        return;
    }

    bayesian_data_training_pair_subscription_t *h = (bayesian_data_training_pair_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    bayesian_data_training_pair_decode_cleanup (&p);
}

bayesian_data_training_pair_subscription_t* bayesian_data_training_pair_subscribe (lcm_t *lcm,
                    const char *channel,
                    bayesian_data_training_pair_handler_t f, void *userdata)
{
    bayesian_data_training_pair_subscription_t *n = (bayesian_data_training_pair_subscription_t*)
                       malloc(sizeof(bayesian_data_training_pair_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 bayesian_data_training_pair_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg bayesian_data_training_pair LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int bayesian_data_training_pair_subscription_set_queue_capacity (bayesian_data_training_pair_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int bayesian_data_training_pair_unsubscribe(lcm_t *lcm, bayesian_data_training_pair_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe bayesian_data_training_pair_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

