// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#ifndef _bayesian_data_training_pair_h
#define _bayesian_data_training_pair_h

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _bayesian_data_training_pair bayesian_data_training_pair;
struct _bayesian_data_training_pair
{
    double     training_x_[5];
    double     training_y_;
};

/**
 * Create a deep copy of a bayesian_data_training_pair.
 * When no longer needed, destroy it with bayesian_data_training_pair_destroy()
 */
bayesian_data_training_pair* bayesian_data_training_pair_copy(const bayesian_data_training_pair* to_copy);

/**
 * Destroy an instance of bayesian_data_training_pair created by bayesian_data_training_pair_copy()
 */
void bayesian_data_training_pair_destroy(bayesian_data_training_pair* to_destroy);

/**
 * Identifies a single subscription.  This is an opaque data type.
 */
typedef struct _bayesian_data_training_pair_subscription_t bayesian_data_training_pair_subscription_t;

/**
 * Prototype for a callback function invoked when a message of type
 * bayesian_data_training_pair is received.
 */
typedef void(*bayesian_data_training_pair_handler_t)(
    const lcm_recv_buf_t *rbuf, const char *channel,
    const bayesian_data_training_pair *msg, void *userdata);

/**
 * Publish a message of type bayesian_data_training_pair using LCM.
 *
 * @param lcm The LCM instance to publish with.
 * @param channel The channel to publish on.
 * @param msg The message to publish.
 * @return 0 on success, <0 on error.  Success means LCM has transferred
 * responsibility of the message data to the OS.
 */
int bayesian_data_training_pair_publish(lcm_t *lcm, const char *channel, const bayesian_data_training_pair *msg);

/**
 * Subscribe to messages of type bayesian_data_training_pair using LCM.
 *
 * @param lcm The LCM instance to subscribe with.
 * @param channel The channel to subscribe to.
 * @param handler The callback function invoked by LCM when a message is
 *     received. This function is invoked by LCM during calls to lcm_handle()
 *     and lcm_handle_timeout().
 * @param userdata An opaque pointer passed to @p handler when it is invoked.
 * @return 0 on success, <0 if an error occured
 */
bayesian_data_training_pair_subscription_t* bayesian_data_training_pair_subscribe(
    lcm_t *lcm, const char *channel, bayesian_data_training_pair_handler_t handler, void *userdata);

/**
 * Removes and destroys a subscription created by bayesian_data_training_pair_subscribe()
 */
int bayesian_data_training_pair_unsubscribe(lcm_t *lcm, bayesian_data_training_pair_subscription_t* hid);

/**
 * Sets the queue capacity for a subscription.
 * Some LCM providers (e.g., the default multicast provider) are implemented
 * using a background receive thread that constantly revceives messages from
 * the network.  As these messages are received, they are buffered on
 * per-subscription queues until dispatched by lcm_handle().  This function
 * how many messages are queued before dropping messages.
 *
 * @param subs the subscription to modify.
 * @param num_messages The maximum number of messages to queue
 *  on the subscription.
 * @return 0 on success, <0 if an error occured
 */
int bayesian_data_training_pair_subscription_set_queue_capacity(
    bayesian_data_training_pair_subscription_t* subs, int num_messages);

/**
 * Encode a message of type bayesian_data_training_pair into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to bayesian_data_training_pair_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int bayesian_data_training_pair_encode(void *buf, int offset, int maxlen, const bayesian_data_training_pair *p);

/**
 * Decode a message of type bayesian_data_training_pair from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with bayesian_data_training_pair_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int bayesian_data_training_pair_decode(const void *buf, int offset, int maxlen, bayesian_data_training_pair *msg);

/**
 * Release resources allocated by bayesian_data_training_pair_decode()
 * @return 0
 */
int bayesian_data_training_pair_decode_cleanup(bayesian_data_training_pair *p);

/**
 * Check how many bytes are required to encode a message of type bayesian_data_training_pair
 */
int bayesian_data_training_pair_encoded_size(const bayesian_data_training_pair *p);

// LCM support functions. Users should not call these
int64_t __bayesian_data_training_pair_get_hash(void);
uint64_t __bayesian_data_training_pair_hash_recursive(const __lcm_hash_ptr *p);
int __bayesian_data_training_pair_encode_array(
    void *buf, int offset, int maxlen, const bayesian_data_training_pair *p, int elements);
int __bayesian_data_training_pair_decode_array(
    const void *buf, int offset, int maxlen, bayesian_data_training_pair *p, int elements);
int __bayesian_data_training_pair_decode_array_cleanup(bayesian_data_training_pair *p, int elements);
int __bayesian_data_training_pair_encoded_array_size(const bayesian_data_training_pair *p, int elements);
int __bayesian_data_training_pair_clone_array(const bayesian_data_training_pair *p, bayesian_data_training_pair *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
