// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#ifndef _distribution_data_path_dist_h
#define _distribution_data_path_dist_h

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifdef __cplusplus
extern "C" {
#endif

#include "lcmtypes/distribution_data_sample.h"
typedef struct _distribution_data_path_dist distribution_data_path_dist;
struct _distribution_data_path_dist
{
    int32_t    num_sample;
    distribution_data_sample *cost_dist;
};

/**
 * Create a deep copy of a distribution_data_path_dist.
 * When no longer needed, destroy it with distribution_data_path_dist_destroy()
 */
distribution_data_path_dist* distribution_data_path_dist_copy(const distribution_data_path_dist* to_copy);

/**
 * Destroy an instance of distribution_data_path_dist created by distribution_data_path_dist_copy()
 */
void distribution_data_path_dist_destroy(distribution_data_path_dist* to_destroy);

/**
 * Identifies a single subscription.  This is an opaque data type.
 */
typedef struct _distribution_data_path_dist_subscription_t distribution_data_path_dist_subscription_t;

/**
 * Prototype for a callback function invoked when a message of type
 * distribution_data_path_dist is received.
 */
typedef void(*distribution_data_path_dist_handler_t)(
    const lcm_recv_buf_t *rbuf, const char *channel,
    const distribution_data_path_dist *msg, void *userdata);

/**
 * Publish a message of type distribution_data_path_dist using LCM.
 *
 * @param lcm The LCM instance to publish with.
 * @param channel The channel to publish on.
 * @param msg The message to publish.
 * @return 0 on success, <0 on error.  Success means LCM has transferred
 * responsibility of the message data to the OS.
 */
int distribution_data_path_dist_publish(lcm_t *lcm, const char *channel, const distribution_data_path_dist *msg);

/**
 * Subscribe to messages of type distribution_data_path_dist using LCM.
 *
 * @param lcm The LCM instance to subscribe with.
 * @param channel The channel to subscribe to.
 * @param handler The callback function invoked by LCM when a message is
 *     received. This function is invoked by LCM during calls to lcm_handle()
 *     and lcm_handle_timeout().
 * @param userdata An opaque pointer passed to @p handler when it is invoked.
 * @return 0 on success, <0 if an error occured
 */
distribution_data_path_dist_subscription_t* distribution_data_path_dist_subscribe(
    lcm_t *lcm, const char *channel, distribution_data_path_dist_handler_t handler, void *userdata);

/**
 * Removes and destroys a subscription created by distribution_data_path_dist_subscribe()
 */
int distribution_data_path_dist_unsubscribe(lcm_t *lcm, distribution_data_path_dist_subscription_t* hid);

/**
 * Sets the queue capacity for a subscription.
 * Some LCM providers (e.g., the default multicast provider) are implemented
 * using a background receive thread that constantly revceives messages from
 * the network.  As these messages are received, they are buffered on
 * per-subscription queues until dispatched by lcm_handle().  This function
 * how many messages are queued before dropping messages.
 *
 * @param subs the subscription to modify.
 * @param num_messages The maximum number of messages to queue
 *  on the subscription.
 * @return 0 on success, <0 if an error occured
 */
int distribution_data_path_dist_subscription_set_queue_capacity(
    distribution_data_path_dist_subscription_t* subs, int num_messages);

/**
 * Encode a message of type distribution_data_path_dist into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to distribution_data_path_dist_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int distribution_data_path_dist_encode(void *buf, int offset, int maxlen, const distribution_data_path_dist *p);

/**
 * Decode a message of type distribution_data_path_dist from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with distribution_data_path_dist_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int distribution_data_path_dist_decode(const void *buf, int offset, int maxlen, distribution_data_path_dist *msg);

/**
 * Release resources allocated by distribution_data_path_dist_decode()
 * @return 0
 */
int distribution_data_path_dist_decode_cleanup(distribution_data_path_dist *p);

/**
 * Check how many bytes are required to encode a message of type distribution_data_path_dist
 */
int distribution_data_path_dist_encoded_size(const distribution_data_path_dist *p);

// LCM support functions. Users should not call these
int64_t __distribution_data_path_dist_get_hash(void);
uint64_t __distribution_data_path_dist_hash_recursive(const __lcm_hash_ptr *p);
int __distribution_data_path_dist_encode_array(
    void *buf, int offset, int maxlen, const distribution_data_path_dist *p, int elements);
int __distribution_data_path_dist_decode_array(
    const void *buf, int offset, int maxlen, distribution_data_path_dist *p, int elements);
int __distribution_data_path_dist_decode_array_cleanup(distribution_data_path_dist *p, int elements);
int __distribution_data_path_dist_encoded_array_size(const distribution_data_path_dist *p, int elements);
int __distribution_data_path_dist_clone_array(const distribution_data_path_dist *p, distribution_data_path_dist *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
