// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "lcmtypes/distribution_data_sample.h"

static int __distribution_data_sample_hash_computed;
static uint64_t __distribution_data_sample_hash;

uint64_t __distribution_data_sample_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __distribution_data_sample_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = __distribution_data_sample_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x3a9f3df40509e025LL
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __distribution_data_sample_get_hash(void)
{
    if (!__distribution_data_sample_hash_computed) {
        __distribution_data_sample_hash = (int64_t)__distribution_data_sample_hash_recursive(NULL);
        __distribution_data_sample_hash_computed = 1;
    }

    return __distribution_data_sample_hash;
}

int __distribution_data_sample_encode_array(void *buf, int offset, int maxlen, const distribution_data_sample *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].cost), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].p), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int distribution_data_sample_encode(void *buf, int offset, int maxlen, const distribution_data_sample *p)
{
    int pos = 0, thislen;
    int64_t hash = __distribution_data_sample_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __distribution_data_sample_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __distribution_data_sample_encoded_array_size(const distribution_data_sample *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __double_encoded_array_size(&(p[element].cost), 1);

        size += __double_encoded_array_size(&(p[element].p), 1);

    }
    return size;
}

int distribution_data_sample_encoded_size(const distribution_data_sample *p)
{
    return 8 + __distribution_data_sample_encoded_array_size(p, 1);
}

int __distribution_data_sample_decode_array(const void *buf, int offset, int maxlen, distribution_data_sample *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].cost), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].p), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __distribution_data_sample_decode_array_cleanup(distribution_data_sample *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __double_decode_array_cleanup(&(p[element].cost), 1);

        __double_decode_array_cleanup(&(p[element].p), 1);

    }
    return 0;
}

int distribution_data_sample_decode(const void *buf, int offset, int maxlen, distribution_data_sample *p)
{
    int pos = 0, thislen;
    int64_t hash = __distribution_data_sample_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __distribution_data_sample_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int distribution_data_sample_decode_cleanup(distribution_data_sample *p)
{
    return __distribution_data_sample_decode_array_cleanup(p, 1);
}

int __distribution_data_sample_clone_array(const distribution_data_sample *p, distribution_data_sample *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __double_clone_array(&(p[element].cost), &(q[element].cost), 1);

        __double_clone_array(&(p[element].p), &(q[element].p), 1);

    }
    return 0;
}

distribution_data_sample *distribution_data_sample_copy(const distribution_data_sample *p)
{
    distribution_data_sample *q = (distribution_data_sample*) malloc(sizeof(distribution_data_sample));
    __distribution_data_sample_clone_array(p, q, 1);
    return q;
}

void distribution_data_sample_destroy(distribution_data_sample *p)
{
    __distribution_data_sample_decode_array_cleanup(p, 1);
    free(p);
}

int distribution_data_sample_publish(lcm_t *lc, const char *channel, const distribution_data_sample *p)
{
      int max_data_size = distribution_data_sample_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = distribution_data_sample_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _distribution_data_sample_subscription_t {
    distribution_data_sample_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void distribution_data_sample_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    distribution_data_sample p;
    memset(&p, 0, sizeof(distribution_data_sample));
    status = distribution_data_sample_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding distribution_data_sample!!!\n", status);
        return;
    }

    distribution_data_sample_subscription_t *h = (distribution_data_sample_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    distribution_data_sample_decode_cleanup (&p);
}

distribution_data_sample_subscription_t* distribution_data_sample_subscribe (lcm_t *lcm,
                    const char *channel,
                    distribution_data_sample_handler_t f, void *userdata)
{
    distribution_data_sample_subscription_t *n = (distribution_data_sample_subscription_t*)
                       malloc(sizeof(distribution_data_sample_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 distribution_data_sample_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg distribution_data_sample LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int distribution_data_sample_subscription_set_queue_capacity (distribution_data_sample_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int distribution_data_sample_unsubscribe(lcm_t *lcm, distribution_data_sample_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe distribution_data_sample_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

