/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package bayesian_data;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class bayesian_flag implements lcm.lcm.LCMEncodable
{
    public boolean bayesian_opt_flag;
 
    public bayesian_flag()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x296023e0845baad8L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(bayesian_data.bayesian_flag.class))
            return 0L;
 
        classes.add(bayesian_data.bayesian_flag.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeByte( this.bayesian_opt_flag ? 1 : 0); 
 
    }
 
    public bayesian_flag(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public bayesian_flag(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static bayesian_data.bayesian_flag _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        bayesian_data.bayesian_flag o = new bayesian_data.bayesian_flag();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.bayesian_opt_flag = ins.readByte()!=0;
 
    }
 
    public bayesian_data.bayesian_flag copy()
    {
        bayesian_data.bayesian_flag outobj = new bayesian_data.bayesian_flag();
        outobj.bayesian_opt_flag = this.bayesian_opt_flag;
 
        return outobj;
    }
 
}

