/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package bayesian_data;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class nzig_data implements lcm.lcm.LCMEncodable
{
    public int num_nzig_;
    public long nzig_[];
 
    public nzig_data()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xefd073321198f0c1L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(bayesian_data.nzig_data.class))
            return 0L;
 
        classes.add(bayesian_data.nzig_data.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeInt(this.num_nzig_); 
 
        for (int a = 0; a < this.num_nzig_; a++) {
            outs.writeLong(this.nzig_[a]); 
        }
 
    }
 
    public nzig_data(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public nzig_data(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static bayesian_data.nzig_data _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        bayesian_data.nzig_data o = new bayesian_data.nzig_data();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.num_nzig_ = ins.readInt();
 
        this.nzig_ = new long[(int) num_nzig_];
        for (int a = 0; a < this.num_nzig_; a++) {
            this.nzig_[a] = ins.readLong();
        }
 
    }
 
    public bayesian_data.nzig_data copy()
    {
        bayesian_data.nzig_data outobj = new bayesian_data.nzig_data();
        outobj.num_nzig_ = this.num_nzig_;
 
        outobj.nzig_ = new long[(int) num_nzig_];
        if (this.num_nzig_ > 0)
            System.arraycopy(this.nzig_, 0, outobj.nzig_, 0, this.num_nzig_); 
        return outobj;
    }
 
}

