/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package bayesian_data;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class probability_data implements lcm.lcm.LCMEncodable
{
    public int num_probs_;
    public double probs_[];
 
    public probability_data()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x5efcf92981c8c738L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(bayesian_data.probability_data.class))
            return 0L;
 
        classes.add(bayesian_data.probability_data.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeInt(this.num_probs_); 
 
        for (int a = 0; a < this.num_probs_; a++) {
            outs.writeDouble(this.probs_[a]); 
        }
 
    }
 
    public probability_data(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public probability_data(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static bayesian_data.probability_data _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        bayesian_data.probability_data o = new bayesian_data.probability_data();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.num_probs_ = ins.readInt();
 
        this.probs_ = new double[(int) num_probs_];
        for (int a = 0; a < this.num_probs_; a++) {
            this.probs_[a] = ins.readDouble();
        }
 
    }
 
    public bayesian_data.probability_data copy()
    {
        bayesian_data.probability_data outobj = new bayesian_data.probability_data();
        outobj.num_probs_ = this.num_probs_;
 
        outobj.probs_ = new double[(int) num_probs_];
        if (this.num_probs_ > 0)
            System.arraycopy(this.probs_, 0, outobj.probs_, 0, this.num_probs_); 
        return outobj;
    }
 
}

