/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package graph_data;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class entropy_paths_trend_data implements lcm.lcm.LCMEncodable
{
    public int num_path_;
    public graph_data.entropy_path_trend_data entropy_paths_[];
 
    public entropy_paths_trend_data()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xf1223a9b5bea0642L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(graph_data.entropy_paths_trend_data.class))
            return 0L;
 
        classes.add(graph_data.entropy_paths_trend_data.class);
        long hash = LCM_FINGERPRINT_BASE
             + graph_data.entropy_path_trend_data._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeInt(this.num_path_); 
 
        for (int a = 0; a < this.num_path_; a++) {
            this.entropy_paths_[a]._encodeRecursive(outs); 
        }
 
    }
 
    public entropy_paths_trend_data(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public entropy_paths_trend_data(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static graph_data.entropy_paths_trend_data _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        graph_data.entropy_paths_trend_data o = new graph_data.entropy_paths_trend_data();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.num_path_ = ins.readInt();
 
        this.entropy_paths_ = new graph_data.entropy_path_trend_data[(int) num_path_];
        for (int a = 0; a < this.num_path_; a++) {
            this.entropy_paths_[a] = graph_data.entropy_path_trend_data._decodeRecursiveFactory(ins);
        }
 
    }
 
    public graph_data.entropy_paths_trend_data copy()
    {
        graph_data.entropy_paths_trend_data outobj = new graph_data.entropy_paths_trend_data();
        outobj.num_path_ = this.num_path_;
 
        outobj.entropy_paths_ = new graph_data.entropy_path_trend_data[(int) num_path_];
        for (int a = 0; a < this.num_path_; a++) {
            outobj.entropy_paths_[a] = this.entropy_paths_[a].copy();
        }
 
        return outobj;
    }
 
}

