/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package graph_data;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class local_hspts_data implements lcm.lcm.LCMEncodable
{
    public int num_spts_;
    public long hspts_[];
 
    public local_hspts_data()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x7e0ebcf32d0438f7L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(graph_data.local_hspts_data.class))
            return 0L;
 
        classes.add(graph_data.local_hspts_data.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeInt(this.num_spts_); 
 
        for (int a = 0; a < this.num_spts_; a++) {
            outs.writeLong(this.hspts_[a]); 
        }
 
    }
 
    public local_hspts_data(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public local_hspts_data(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static graph_data.local_hspts_data _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        graph_data.local_hspts_data o = new graph_data.local_hspts_data();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.num_spts_ = ins.readInt();
 
        this.hspts_ = new long[(int) num_spts_];
        for (int a = 0; a < this.num_spts_; a++) {
            this.hspts_[a] = ins.readLong();
        }
 
    }
 
    public graph_data.local_hspts_data copy()
    {
        graph_data.local_hspts_data outobj = new graph_data.local_hspts_data();
        outobj.num_spts_ = this.num_spts_;
 
        outobj.hspts_ = new long[(int) num_spts_];
        if (this.num_spts_ > 0)
            System.arraycopy(this.hspts_, 0, outobj.hspts_, 0, this.num_spts_); 
        return outobj;
    }
 
}

