/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package graph_data;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class map_data implements lcm.lcm.LCMEncodable
{
    public long num_v_;
    public graph_data.vertex_data vertex_[];
 
    public map_data()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x1b4d686d48fd87f0L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(graph_data.map_data.class))
            return 0L;
 
        classes.add(graph_data.map_data.class);
        long hash = LCM_FINGERPRINT_BASE
             + graph_data.vertex_data._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.num_v_); 
 
        for (int a = 0; a < this.num_v_; a++) {
            this.vertex_[a]._encodeRecursive(outs); 
        }
 
    }
 
    public map_data(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public map_data(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static graph_data.map_data _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        graph_data.map_data o = new graph_data.map_data();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.num_v_ = ins.readLong();
 
        this.vertex_ = new graph_data.vertex_data[(int) num_v_];
        for (int a = 0; a < this.num_v_; a++) {
            this.vertex_[a] = graph_data.vertex_data._decodeRecursiveFactory(ins);
        }
 
    }
 
    public graph_data.map_data copy()
    {
        graph_data.map_data outobj = new graph_data.map_data();
        outobj.num_v_ = this.num_v_;
 
        outobj.vertex_ = new graph_data.vertex_data[(int) num_v_];
        for (int a = 0; a < this.num_v_; a++) {
            outobj.vertex_[a] = this.vertex_[a].copy();
        }
 
        return outobj;
    }
 
}

