/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package graph_data;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class paths_data implements lcm.lcm.LCMEncodable
{
    public int num_path_;
    public graph_data.path_data path_collection_[];
 
    public paths_data()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x842ca2b52f1f33ffL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(graph_data.paths_data.class))
            return 0L;
 
        classes.add(graph_data.paths_data.class);
        long hash = LCM_FINGERPRINT_BASE
             + graph_data.path_data._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeInt(this.num_path_); 
 
        for (int a = 0; a < this.num_path_; a++) {
            this.path_collection_[a]._encodeRecursive(outs); 
        }
 
    }
 
    public paths_data(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public paths_data(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static graph_data.paths_data _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        graph_data.paths_data o = new graph_data.paths_data();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.num_path_ = ins.readInt();
 
        this.path_collection_ = new graph_data.path_data[(int) num_path_];
        for (int a = 0; a < this.num_path_; a++) {
            this.path_collection_[a] = graph_data.path_data._decodeRecursiveFactory(ins);
        }
 
    }
 
    public graph_data.paths_data copy()
    {
        graph_data.paths_data outobj = new graph_data.paths_data();
        outobj.num_path_ = this.num_path_;
 
        outobj.path_collection_ = new graph_data.path_data[(int) num_path_];
        for (int a = 0; a < this.num_path_; a++) {
            outobj.path_collection_[a] = this.path_collection_[a].copy();
        }
 
        return outobj;
    }
 
}

