"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import random_graph_data.agent_data

class agents_data(object):
    __slots__ = ["num_agents_", "agents_"]

    __typenames__ = ["int8_t", "random_graph_data.agent_data"]

    __dimensions__ = [None, ["num_agents_"]]

    def __init__(self):
        self.num_agents_ = 0
        self.agents_ = []

    def encode(self):
        buf = BytesIO()
        buf.write(agents_data._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">b", self.num_agents_))
        for i0 in range(self.num_agents_):
            assert self.agents_[i0]._get_packed_fingerprint() == random_graph_data.agent_data._get_packed_fingerprint()
            self.agents_[i0]._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != agents_data._get_packed_fingerprint():
            raise ValueError("Decode error")
        return agents_data._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = agents_data()
        self.num_agents_ = struct.unpack(">b", buf.read(1))[0]
        self.agents_ = []
        for i0 in range(self.num_agents_):
            self.agents_.append(random_graph_data.agent_data._decode_one(buf))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if agents_data in parents: return 0
        newparents = parents + [agents_data]
        tmphash = (0x85f3bd8986d5e356+ random_graph_data.agent_data._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if agents_data._packed_fingerprint is None:
            agents_data._packed_fingerprint = struct.pack(">Q", agents_data._get_hash_recursive([]))
        return agents_data._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

