"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class task_data(object):
    __slots__ = ["target_pos_", "idx_"]

    __typenames__ = ["int64_t", "int64_t"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.target_pos_ = 0
        self.idx_ = 0

    def encode(self):
        buf = BytesIO()
        buf.write(task_data._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qq", self.target_pos_, self.idx_))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != task_data._get_packed_fingerprint():
            raise ValueError("Decode error")
        return task_data._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = task_data()
        self.target_pos_, self.idx_ = struct.unpack(">qq", buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if task_data in parents: return 0
        tmphash = (0x6e0dabb31cc0c5de) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if task_data._packed_fingerprint is None:
            task_data._packed_fingerprint = struct.pack(">Q", task_data._get_hash_recursive([]))
        return task_data._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

