"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class local_hspts_data(object):
    __slots__ = ["num_spts_", "hspts_"]

    __typenames__ = ["int32_t", "int64_t"]

    __dimensions__ = [None, ["num_spts_"]]

    def __init__(self):
        self.num_spts_ = 0
        self.hspts_ = []

    def encode(self):
        buf = BytesIO()
        buf.write(local_hspts_data._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.num_spts_))
        buf.write(struct.pack('>%dq' % self.num_spts_, *self.hspts_[:self.num_spts_]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != local_hspts_data._get_packed_fingerprint():
            raise ValueError("Decode error")
        return local_hspts_data._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = local_hspts_data()
        self.num_spts_ = struct.unpack(">i", buf.read(4))[0]
        self.hspts_ = struct.unpack('>%dq' % self.num_spts_, buf.read(self.num_spts_ * 8))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if local_hspts_data in parents: return 0
        tmphash = (0x7e0ebcf32d0438f7) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if local_hspts_data._packed_fingerprint is None:
            local_hspts_data._packed_fingerprint = struct.pack(">Q", local_hspts_data._get_hash_recursive([]))
        return local_hspts_data._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

