"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import graph_data.vertex_data

class map_data(object):
    __slots__ = ["num_v_", "vertex_"]

    __typenames__ = ["int64_t", "graph_data.vertex_data"]

    __dimensions__ = [None, ["num_v_"]]

    def __init__(self):
        self.num_v_ = 0
        self.vertex_ = []

    def encode(self):
        buf = BytesIO()
        buf.write(map_data._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.num_v_))
        for i0 in range(self.num_v_):
            assert self.vertex_[i0]._get_packed_fingerprint() == graph_data.vertex_data._get_packed_fingerprint()
            self.vertex_[i0]._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != map_data._get_packed_fingerprint():
            raise ValueError("Decode error")
        return map_data._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = map_data()
        self.num_v_ = struct.unpack(">q", buf.read(8))[0]
        self.vertex_ = []
        for i0 in range(self.num_v_):
            self.vertex_.append(graph_data.vertex_data._decode_one(buf))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if map_data in parents: return 0
        newparents = parents + [map_data]
        tmphash = (0x1b4d686d48fd87f0+ graph_data.vertex_data._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if map_data._packed_fingerprint is None:
            map_data._packed_fingerprint = struct.pack(">Q", map_data._get_hash_recursive([]))
        return map_data._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

