"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import graph_data.path_data

class paths_data(object):
    __slots__ = ["num_path_", "path_collection_"]

    __typenames__ = ["int32_t", "graph_data.path_data"]

    __dimensions__ = [None, ["num_path_"]]

    def __init__(self):
        self.num_path_ = 0
        self.path_collection_ = []

    def encode(self):
        buf = BytesIO()
        buf.write(paths_data._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.num_path_))
        for i0 in range(self.num_path_):
            assert self.path_collection_[i0]._get_packed_fingerprint() == graph_data.path_data._get_packed_fingerprint()
            self.path_collection_[i0]._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != paths_data._get_packed_fingerprint():
            raise ValueError("Decode error")
        return paths_data._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = paths_data()
        self.num_path_ = struct.unpack(">i", buf.read(4))[0]
        self.path_collection_ = []
        for i0 in range(self.num_path_):
            self.path_collection_.append(graph_data.path_data._decode_one(buf))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if paths_data in parents: return 0
        newparents = parents + [paths_data]
        tmphash = (0x842ca2b52f1f33ff+ graph_data.path_data._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if paths_data._packed_fingerprint is None:
            paths_data._packed_fingerprint = struct.pack(">Q", paths_data._get_hash_recursive([]))
        return paths_data._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

