"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class range_checked_data(object):
    __slots__ = ["num_iteration_", "range_"]

    __typenames__ = ["int32_t", "int64_t"]

    __dimensions__ = [None, ["num_iteration_"]]

    def __init__(self):
        self.num_iteration_ = 0
        self.range_ = []

    def encode(self):
        buf = BytesIO()
        buf.write(range_checked_data._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.num_iteration_))
        buf.write(struct.pack('>%dq' % self.num_iteration_, *self.range_[:self.num_iteration_]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != range_checked_data._get_packed_fingerprint():
            raise ValueError("Decode error")
        return range_checked_data._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = range_checked_data()
        self.num_iteration_ = struct.unpack(">i", buf.read(4))[0]
        self.range_ = struct.unpack('>%dq' % self.num_iteration_, buf.read(self.num_iteration_ * 8))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if range_checked_data in parents: return 0
        tmphash = (0x5e5b4862667bb4f8) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if range_checked_data._packed_fingerprint is None:
            range_checked_data._packed_fingerprint = struct.pack(">Q", range_checked_data._get_hash_recursive([]))
        return range_checked_data._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

