"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class sensors_data(object):
    __slots__ = ["num_sensor_", "sensor_pos_"]

    __typenames__ = ["int32_t", "int64_t"]

    __dimensions__ = [None, ["num_sensor_"]]

    def __init__(self):
        self.num_sensor_ = 0
        self.sensor_pos_ = []

    def encode(self):
        buf = BytesIO()
        buf.write(sensors_data._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.num_sensor_))
        buf.write(struct.pack('>%dq' % self.num_sensor_, *self.sensor_pos_[:self.num_sensor_]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != sensors_data._get_packed_fingerprint():
            raise ValueError("Decode error")
        return sensors_data._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = sensors_data()
        self.num_sensor_ = struct.unpack(">i", buf.read(4))[0]
        self.sensor_pos_ = struct.unpack('>%dq' % self.num_sensor_, buf.read(self.num_sensor_ * 8))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if sensors_data in parents: return 0
        tmphash = (0x5306c73bdf14677d) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if sensors_data._packed_fingerprint is None:
            sensors_data._packed_fingerprint = struct.pack(">Q", sensors_data._get_hash_recursive([]))
        return sensors_data._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

