"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class sample(object):
    __slots__ = ["cost", "p"]

    __typenames__ = ["double", "double"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.cost = 0.0
        self.p = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(sample._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">dd", self.cost, self.p))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != sample._get_packed_fingerprint():
            raise ValueError("Decode error")
        return sample._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = sample()
        self.cost, self.p = struct.unpack(">dd", buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if sample in parents: return 0
        tmphash = (0x3a9f3df40509e025) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if sample._packed_fingerprint is None:
            sample._packed_fingerprint = struct.pack(">Q", sample._get_hash_recursive([]))
        return sample._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

