"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class bayesian_flag(object):
    __slots__ = ["bayesian_opt_flag"]

    __typenames__ = ["boolean"]

    __dimensions__ = [None]

    def __init__(self):
        self.bayesian_opt_flag = False

    def encode(self):
        buf = BytesIO()
        buf.write(bayesian_flag._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">b", self.bayesian_opt_flag))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != bayesian_flag._get_packed_fingerprint():
            raise ValueError("Decode error")
        return bayesian_flag._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = bayesian_flag()
        self.bayesian_opt_flag = bool(struct.unpack('b', buf.read(1))[0])
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if bayesian_flag in parents: return 0
        tmphash = (0x296023e0845baad8) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if bayesian_flag._packed_fingerprint is None:
            bayesian_flag._packed_fingerprint = struct.pack(">Q", bayesian_flag._get_hash_recursive([]))
        return bayesian_flag._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

