"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class training_pair(object):
    __slots__ = ["training_x_", "training_y_"]

    __typenames__ = ["double", "double"]

    __dimensions__ = [[5], None]

    def __init__(self):
        self.training_x_ = [ 0.0 for dim0 in range(5) ]
        self.training_y_ = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(training_pair._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>5d', *self.training_x_[:5]))
        buf.write(struct.pack(">d", self.training_y_))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != training_pair._get_packed_fingerprint():
            raise ValueError("Decode error")
        return training_pair._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = training_pair()
        self.training_x_ = struct.unpack('>5d', buf.read(40))
        self.training_y_ = struct.unpack(">d", buf.read(8))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if training_pair in parents: return 0
        tmphash = (0xe86f2ac9014a632) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if training_pair._packed_fingerprint is None:
            training_pair._packed_fingerprint = struct.pack(">Q", training_pair._get_hash_recursive([]))
        return training_pair._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

